### ISSUE TITLE
加载辅助类

### ISSUE THREAD

**Issue by RoyLin1994** [ShawnWu20147/GestureAnalysis#1]
嗨，看到你的这个repo。里面有个addBasicClass跟setApplicationClass这两个api的调用。应该是用来加载自己写好的辅助类。我在这里遇到了问题，请问是否可以留下你的联系方式，向你请教下呢？

**Comment by ShawnWu20147** [comment]
我的邮箱是shawnwu20147@gmail.com 或者 wuxiangyu666@sina.com 。 另外问一下，你也是用Soot做一些有趣的事情的么？
